name: handle-generation

on:
  workflow_dispatch:
      iterations:
        description: 'Number of handles to generate'
        default: 1
        required: true
        type: number

jobs:
  generate-handles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python obp_handle_generator ${{ inputs.iterations }}
