name: handle-generation

on:
  workflow_dispatch:
    inputs:
      iterations:
        description: 'Number of handles to generate'
        default: 1
        required: true
        type: number

jobs:
  generate-handles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Run handle generator and save summary
        run: |
          OUTPUT=$(python obp_handle_generator ${{ inputs.iterations }})
          echo "### Handles" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "$OUTPUT" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
